include-file = ./gruvbox.ini

[bar/main]
width = 100%
height = 24pt
radius = 0

dpi = 144

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:size=12;2"

modules-left = i3
modules-center = date
modules-right = alsa-mic xkeyboard memory cpu fs alsa network 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/i3]
type = internal/i3

pin-workspaces = true
index-sort = true
enable-click = true
enable-scroll = false

label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.background}
label-mode-foreground = ${colors.alert}

label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-unfocused = %index%
label-unfocused-padding = 1

label-visible = %index%
label-visible-underline = ${colors.secondary}
label-visible-padding = 1

label-urgent = %index%
label-urgent-foreground = ${colors.background}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/date]
type = internal/date
interval = 60
date = %A, %d %B %Y
time = %I:%M %p
date-alt = %Y-%m-%d
time-alt = %I:%M %p
label = %date% %time%

[module/network]
type = internal/network
interface-type = wired
interval = 3.0
label-connected = "󰈁"
label-connected-foreground = ${colors.green}
label-disconnected = "󰈂"
label-disconnected-foreground = ${colors.disabled}

[module/fs]
type = internal/fs
mount-0 = /
interval = 30
label-mounted = %mountpoint%: %free%
label-unmounted = %mountpoint%: not mounted
label-unmounted-foreground = ${colors.disabled}

[module/cpu]
type = internal/cpu
label =  %percentage%%
label-warn =  %percentage%%

[module/memory]
type = internal/memory
label = 󰘚 %used%
label-warn = 󰘚 %used%

[module/alsa]
type = internal/alsa
label-volume = 󰕾 %percentage%%
label-muted = "󰖁 muted"
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard

; Ignore number lock and scroll lock so they don't clutter the bar
blacklist-0 = num lock
blacklist-1 = scroll lock

format = <label-layout> <label-indicator>

layout-icon-0 = us;en
layout-icon-1 = ara;ar 
layout-icon-default =
label-layout =  %icon%
label-layout-foreground = ${colors.foreground}

label-indicator-on-capslock = CAPS
label-indicator-on-capslock-foreground = ${colors.alert}
label-indicator-off-capslock =

[module/alsa-mic]
type = custom/ipc
hook-0 = wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q MUTED && echo "󰍭" || echo ""
initial = 1
click-left = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && polybar-msg action "#alsa-mic.hook.0"
format-foreground = ${colors.alert}
format-background = ${colors.background}

[settings]
screenchange-reload = true
pseudo-transparency = true
